### PR TITLE
Test inference

### PR DESCRIPTION
**Pull request by AmarensElise**
All the necessary documents are found in the folder named 'assignment 7'.

### CODE REVIEW

**Comment by Lemswasabi** [comment]
Hi @AmarensElise and @cmfuego,

I had a look at your PR. I ran your inference test and I made it work locally and on your provided Google Colab notebook. However, I would like to suggest some changes to make your inference reproduction easier:

1. There is a variable initialization [here](https://github.com/phat-vtcf/NeMo/pull/1/files#diff-b3a18c2ec80181c5276ccd979e4261624af1f5547b1cf0afeeecc816fdc2207bR239) that results in a `ValueError` and stops the whole execution of the inference. You can either provide your `amarens-wind-09092021-spanish.wav` file or remove the initialization so only `tengo-once-anos.mp3` will be used for inference.

2. [Here](https://github.com/phat-vtcf/NeMo/pull/1/files#diff-6f9f836c709713b1a9568163e7b2d5a8f1cbaf13522d0898fb73e04fa78b7da6R18-R24) you suggest we can reproduce the inference in our local environment, thus I would suggest adding a verification if the tester's environment contains a GPU for CUDA operations before the initialization of the models [here](https://github.com/phat-vtcf/NeMo/pull/1/files#diff-6f9f836c709713b1a9568163e7b2d5a8f1cbaf13522d0898fb73e04fa78b7da6R18-R24). The verification could be implemented with the following check:

```python
import torch
torch.cuda.is_available()
```

If the testing environment does not contain CUDA capable GPUs, the models should be initialized without the `.cuda()` method for CPU inference.

@Tatsu1020 Reviewed this PR as well and made the same observations. Perhaps, he might have additional comments.

Overall, this PR LGTM! If you could look at the suggestions and incorporate them, I would approve the merge of this PR.

**Review by lemswasabi — CHANGES_REQUESTED** [review]
Hi @AmarensElise and @cmfuego,

I had a look at your PR. I ran your inference test and I made it work locally and on your provided Google Colab notebook. However, I would like to suggest some changes to make your inference reproduction easier:

1. There is a variable initialization [here](https://github.com/phat-vtcf/NeMo/pull/1/files#diff-b3a18c2ec80181c5276ccd979e4261624af1f5547b1cf0afeeecc816fdc2207bR239) that results in a `ValueError` and stops the whole execution of the inference. You can either provide your `amarens-wind-09092021-spanish.wav` file or remove the initialization so only `tengo-once-anos.mp3` will be used for inference.

2. [Here](https://github.com/phat-vtcf/NeMo/pull/1/files#diff-6f9f836c709713b1a9568163e7b2d5a8f1cbaf13522d0898fb73e04fa78b7da6R18-R24) you suggest we can reproduce the inference in our local environment, thus I would suggest adding a verification if the tester's environment contains a GPU for CUDA operations before the initialization of the models [here](https://github.com/phat-vtcf/NeMo/pull/1/files#diff-b3a18c2ec80181c5276ccd979e4261624af1f5547b1cf0afeeecc816fdc2207bR163-R175). The verification could be implemented with the following check:

```python
import torch
torch.cuda.is_available()
```

If the testing environment does not contain CUDA capable GPUs, the models should be initialized without the `.cuda()` method for CPU inference.

@Tatsu1020 Reviewed this PR as well and made the same observations. Perhaps, he might have additional comments.

Overall, this PR LGTM! If you could look at the suggestions and incorporate them, I would approve the merge of this PR.

**Review by secretlemoncake — COMMENTED** [review]
Hi @AmarensElise and @cmfuego,

I also looked at your PR. As @Lemswasabi mentioned in his reviews, I had the same remarks. 
Therefore,  I would like to give just comments on your PR. Overall, it was effortless to complete the task becuase of your clear instructions in README file. If you incorporate our suggestions into your code, I would also like to approve the merge of the PR!

**Review by AmarensElise — COMMENTED** [review]
Very good suggestions, thank you!

**Comment by cmfuego** [comment]
> 1. There is a variable initialization [here](https://github.com/phat-vtcf/NeMo/pull/1/files#diff-b3a18c2ec80181c5276ccd979e4261624af1f5547b1cf0afeeecc816fdc2207bR239) that results in a `ValueError` and stops the whole execution of the inference. You can either provide your `amarens-wind-09092021-spanish.wav` file or remove the initialization so only `tengo-once-anos.mp3` will be used for inference.

You're right, we forgot to remove it! The problem is solved now.

> 2. [Here](https://github.com/phat-vtcf/NeMo/pull/1/files#diff-6f9f836c709713b1a9568163e7b2d5a8f1cbaf13522d0898fb73e04fa78b7da6R18-R24) you suggest we can reproduce the inference in our local environment, thus I would suggest adding a verification if the tester's environment contains a GPU for CUDA operations before the initialization of the models [here](https://github.com/phat-vtcf/NeMo/pull/1/files#diff-b3a18c2ec80181c5276ccd979e4261624af1f5547b1cf0afeeecc816fdc2207bR163-R175). The verification could be implemented with the following check:
> 
> ```python
> import torch
> torch.cuda.is_available()
> ```
> 
> If the testing environment does not contain CUDA capable GPUs, the models should be initialized without the `.cuda()` method for CPU inference.

You have a good point here. We have tried to incorporate your suggestion, but ultimately came to the conclusion that it was just beyond our understanding. We will try it again later, but for now with the purpose of the current assignment, in order to keep our the instructions in our notebook as clear as possible, we have decided to leave this part out (since we were not able to reproduce it ourselves).

Thank you @Lemswasabi and @Tatsu1020 for the helpful comments!

**Review by cmfuego — APPROVED** [review]

**Comment by AmarensElise** [comment]
@Lemswasabi and @Tatsu1020 

The comments made were clear and the demands were fair. We initially added the way to reproduce locally because we weren’t sure if just the Google Notebook was enough for the assignment, so we included some instructions from the original repo, but to make this branch more replicable we have now removed it. They also helped us improve some other code referring to a file that shouldn’t have been in there, so that was great. 

We think the instructions we got were clear and helpful though, so it’s due to our own limitations we weren’t able to solve all the issues. Maybe the suggestions on this could have been a little more beginner-friendly, but the overall point was good. 

The grade we would suggest is a 9.7

(@phat-vtcf)

**Review by lemswasabi — APPROVED** [review]
> You have a good point here. We have tried to incorporate your suggestion, but ultimately came to the conclusion that it was just beyond our understanding. We will try it again later, but for now with the purpose of the current assignment, in order to keep our the instructions in our notebook as clear as possible, we have decided to leave this part out (since we were not able to reproduce it ourselves).

No worries, this is totally understandable. I can send you a code snippet for this if you need it.

I reviewed the changes and I approve the merge. Just one little thing you should change before @phat-vtcf reviews your assignment, is the following:

image

I think you wanted to comment out Amarens' audio sample in the Google Colab notebook.

@phat-vtcf The PR and requested changes LGTM! I will merge it now.

**Pull request merged**
